<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="9.*" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BfaNet.Application\BfaNet.Application.csproj" />
    <ProjectReference Include="..\..\src\BfaNet.Infrastructure\BfaNet.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\BfaNet.Domain\BfaNet.Domain.csproj" />
    <ProjectReference Include="..\..\src\BfaNet.Api\BfaNet.Api.csproj" />
  </ItemGroup>

</Project>
